services:
  api:
    build:
      context: .
      target: builder
    environment:
      DB_HOST: 'postgres'
      DB_USER: 'postgres'
      DB_PASSWORD: 'password'
      PORT: 8000
    ports:
      - '8000:8000'
    restart: "no"
  postgres:
    image: postgres:13.2-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password