from typing import Callable, Awaitable

from fastapi import FastAPI, Request, Response
from sqlmodel import Session

from facts_publish.src.core.db import engine, session_ctx
from facts_publish.src.api.articles import router as articleapi
from facts_publish.src.api.credentials import router as credentialapi
from facts_publish.src.api.auth import router as authapi


app = FastAPI(title="FACTS Publish",
              description="FACTS Publisher tool")

app.include_router(articleapi)
app.include_router(credentialapi)
app.include_router(authapi)

@app.middleware("http")
async def db_session_handler(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for managing a database session in the context of HTTP requests.

    :param request: The incoming HTTP request.
    :type request: Request
    :param call_next: A callable allowing the request to proceed to the next
        middleware or route handler.
    :type call_next: Callable[[Request], Awaitable[Response]]
    :return: The HTTP response generated by the route handler or subsequent
        middleware.
    :rtype: Response
    """
    with Session(engine) as session:
        session_token = session_ctx.set(session)
        try:
            response = await call_next(request)
            session.commit()
        except Exception as e:
            session.rollback()
            raise
        else:
            return response
        finally:
            session_ctx.reset(session_token)
            session.close()