from typing import Callable, Awaitable

from fastapi import FastAPI, Request, Response, Depends
from sqlmodel import Session, SQLModel

from core.db import engine, session_ctx
from repositories.ebsi_issuer import IssuerClient

app = FastAPI(title="FACTS Publish",
              description="FACTS Publisher tool")


@app.middleware("http")
async def db_session_handler(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for managing a database session in the context of HTTP requests.

    :param request: The incoming HTTP request.
    :type request: Request
    :param call_next: A callable allowing the request to proceed to the next
        middleware or route handler.
    :type call_next: Callable[[Request], Awaitable[Response]]
    :return: The HTTP response generated by the route handler or subsequent
        middleware.
    :rtype: Response
    """
    with Session(engine) as session:
        session_token = session_ctx.set(session)
        try:
            response = await call_next(request)
            session.commit()
        except Exception as e:
            session.rollback()
            raise
        else:
            return response
        finally:
            session_ctx.reset(session_token)
            session.close()

class CredentialSubject(SQLModel):
    subject_did: str
    company_name: str
    company_address: str
    company_vat: str

@app.post("/request_vc")
async def request_vc(payload: CredentialSubject, subject_did: str, issuer_repo: IssuerClient = Depends()):
    return await issuer_repo.request_vc({
        "subject_did": payload.subject_did,
        "credential_subject":{
            "company_name": payload.company_name,
            "company_address": payload.company_address,
            "company_vat": payload.company_vat
        },
        "credential_type": ['VerifiableCredential', 'FACTSPublisherCredential']
    })
