services:
  facts_backend:
    build:
      context: .
      target: builder
    depends_on:
      facts_db:
        condition: service_healthy
    environment:
      DB_HOST: 'facts_db'
      DB_USER: 'facts'
      DB_PASSWORD: 'password'
      DB_NAME: 'facts'
    ports:
      - '8001:8000'
    restart: "no"
  facts_db:
    image: postgres:13.2-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'facts'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'facts'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U facts -d facts" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'