import traceback
from contextlib import asynccontextmanager
from typing import Callable, Awaitable

from fastapi import FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.exc import SQLAlchemyError
from sqlmodel import Session
from starlette.responses import JSONResponse

from facts_backend.src.api.articles import router as articleapi
from facts_backend.src.api.assessments import router as assessmentapi
from facts_backend.src.api.auth import router as authapi
from facts_backend.src.api.credentials import router as credentialapi
from facts_backend.src.core.db import engine, session_ctx
from facts_backend.src.core.exceptions import FACTSError, FACTSRequestError, FACTSNotFoundError, FACTSAuthError, \
    FACTSDuplicateError
from facts_backend.src.repositories import create_db_and_tables


@asynccontextmanager
async def lifespan(app):
    create_db_and_tables()
    yield

app = FastAPI(lifespan=lifespan, title="FACTS",
              description="Facts Authenticity and Credibility Tracking System")
app.include_router(articleapi)
app.include_router(assessmentapi)
app.include_router(credentialapi)
app.include_router(authapi)

def handle_exception(exc: Exception):
    """
    Handles exceptions and returns an appropriate JSON response.

    This function matches the type of the provided exception to determine a
    specific HTTP status code and message. For known exceptions, custom status
    codes and messages are used. Database errors and generic errors are logged
    using traceback. The response is returned as a JSON with a specific format.

    :param exc: An exception to handle.
    :type exc: Exception
    :return: A JSONResponse object containing an HTTP status code and an error
        message describing the exception.
    :rtype: JSONResponse
    """
    status_code = 500
    message = "Internal Server Error"
    if isinstance(exc, FACTSError):
        message = str(exc)
    if isinstance(exc, FACTSRequestError):
        status_code = 400
    elif isinstance(exc, FACTSNotFoundError):
        status_code = 404
    elif isinstance(exc, FACTSAuthError):
        status_code = 401
    elif isinstance(exc, FACTSDuplicateError):
        status_code = 409
    elif isinstance(exc, SQLAlchemyError):
        message = "Database error"

    if status_code == 500 or not isinstance(exc, FACTSError):
        traceback.print_exc()
    return JSONResponse(status_code=status_code, content={"detail": message})

@app.middleware("http")
async def db_session_handler(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for managing a database session in the context of HTTP requests.

    :param request: The incoming HTTP request.
    :type request: Request
    :param call_next: A callable allowing the request to proceed to the next
        middleware or route handler.
    :type call_next: Callable[[Request], Awaitable[Response]]
    :return: The HTTP response generated by the route handler or subsequent
        middleware.
    :rtype: Response
    """
    with Session(engine) as session:
        session_token = session_ctx.set(session)
        try:
            response = await call_next(request)
            session.commit()
        except Exception as e:
            session.rollback()
            return handle_exception(e)
        else:
            return response
        finally:
            session_ctx.reset(session_token)
            session.close()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)
