from contextlib import asynccontextmanager
from typing import Callable, Awaitable

from fastapi import FastAPI, Request, Response, logger
from sqlalchemy.exc import SQLAlchemyError
from sqlmodel import Session, SQLModel
from starlette.responses import JSONResponse

from ebsi_sim.api.authorisation import router as authapp
from ebsi_sim.api.didr import router as didrapp
from ebsi_sim.api.issuer_mock import router as issuerapp
from ebsi_sim.api.tnt import router as tntapp
from ebsi_sim.api.wallet_mock import router as walletapp
from ebsi_sim.core.db import engine, session_ctx
from ebsi_sim.core.exceptions import EBSIError, EBSIRequestError, EBSINotFoundError, EBSIAuthError, EBSIDatabaseError, \
    EBSIDuplicateError


def create_db_and_tables():
    SQLModel.metadata.create_all(engine)

@asynccontextmanager
async def lifespan(app):
    create_db_and_tables()
    yield

app = FastAPI(lifespan=lifespan)
app.include_router(tntapp)
app.include_router(didrapp)
app.include_router(authapp)
app.include_router(walletapp)
app.include_router(issuerapp)


@app.middleware("http")
async def db_session_handler(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for managing a database session in the context of HTTP requests.

    :param request: The incoming HTTP request.
    :type request: Request
    :param call_next: A callable allowing the request to proceed to the next
        middleware or route handler.
    :type call_next: Callable[[Request], Awaitable[Response]]
    :return: The HTTP response generated by the route handler or subsequent
        middleware.
    :rtype: Response
    """
    with Session(engine) as session:
        token = session_ctx.set(session)
        try:
            response = await call_next(request)
            session.commit()
        except EBSIError:
            session.rollback()
            raise
        except SQLAlchemyError:
            session.rollback()
            raise EBSIDatabaseError("Database error")
        except Exception:
            session.rollback()
            raise EBSIError("Internal error")
        finally:
            session_ctx.reset(token)
            session.close()
    return response


@app.exception_handler(Exception)
async def unicorn_exception_handler(request: Request, exc: Exception):

    status_code = 500
    message = "Internal Server Error"
    if isinstance(exc, EBSIError):
        message = str(exc)
    if isinstance(exc, EBSIRequestError):
        status_code = 400
    elif isinstance(exc, EBSINotFoundError):
        status_code = 404
    elif isinstance(exc, EBSIAuthError):
        status_code = 401
    elif isinstance(exc, EBSIDuplicateError):
        status_code = 409

    return JSONResponse(
        status_code=status_code,
        content={"message": message},
    )