from typing import Callable, Awaitable

from fastapi import FastAPI, Request, Response
from sqlmodel import Session

from ebsi_sim.api.tnt import router as tntapp
from ebsi_sim.api.didr import router as didrapp
from ebsi_sim.core.db import engine, session_ctx

app = FastAPI()
app.include_router(tntapp)  
app.include_router(didrapp)

@app.middleware("http")
async def db_session_handler(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for managing a database session in the context of HTTP requests.

    :param request: The incoming HTTP request.
    :type request: Request
    :param call_next: A callable allowing the request to proceed to the next
        middleware or route handler.
    :type call_next: Callable[[Request], Awaitable[Response]]
    :return: The HTTP response generated by the route handler or subsequent
        middleware.
    :rtype: Response
    """
    with Session(engine) as session:
        token = session_ctx.set(session)
        try:
            response = await call_next(request)
        finally:
            session_ctx.reset(token)
            session.close()
    return response