import sys
from contextlib import asynccontextmanager
from typing import Callable, Awaitable

from fastapi import FastAPI, Request, Response
from sqlalchemy.exc import SQLAlchemyError
from sqlmodel import Session
from starlette.responses import JSONResponse

from api.authorisation import router as authapp
from api.didr import router as didrapp
from api.issuer_mock import router as issuerapp
from api.tnt import router as tntapp
from api.wallet_mock import router as walletapp
from core.db import engine, session_ctx
from core.exceptions import EBSIError, EBSIRequestError, EBSINotFoundError, EBSIAuthError, EBSIDuplicateError
from repositories import create_db_and_tables, create_default_data


@asynccontextmanager
async def lifespan(app):
    create_db_and_tables()
    create_default_data()
    yield


app = FastAPI(lifespan=lifespan, title="EBSI SIM",
              description="EBSI SIM is a simulation of the EBSI Blockchain API.")
app.include_router(tntapp)
app.include_router(didrapp)
app.include_router(authapp)
app.include_router(walletapp)
app.include_router(issuerapp)


def handle_exception(exc: Exception):
    status_code = 500
    message = "Internal Server Error"
    if isinstance(exc, EBSIError):
        message = str(exc)
    if isinstance(exc, EBSIRequestError):
        status_code = 400
    elif isinstance(exc, EBSINotFoundError):
        status_code = 404
    elif isinstance(exc, EBSIAuthError):
        status_code = 401
    elif isinstance(exc, EBSIDuplicateError):
        status_code = 409
    elif isinstance(exc, SQLAlchemyError):
        message = "Database error"

    return JSONResponse(status_code=status_code, content={"detail": message})


@app.middleware("http")
async def db_session_handler(request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
    """
    Middleware for managing a database session in the context of HTTP requests.

    :param request: The incoming HTTP request.
    :type request: Request
    :param call_next: A callable allowing the request to proceed to the next
        middleware or route handler.
    :type call_next: Callable[[Request], Awaitable[Response]]
    :return: The HTTP response generated by the route handler or subsequent
        middleware.
    :rtype: Response
    """
    with Session(engine) as session:
        session_token = session_ctx.set(session)
        try:
            response = await call_next(request)
            session.commit()
        except Exception as e:
            session.rollback()
            return handle_exception(e)
        else:
            return response
        finally:
            session_ctx.reset(session_token)
            session.close()